name: deploy-manifest
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install doctl + authenticate
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # Connect to our DO k8s cluster context
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # Apply k8s configs from base + prod
      - run: kubectl apply -f infra/k8s -f infra/k8s-prod
