name: deploy-expiration
on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build docker image, login to dockerhub, and push
      - run: cd expiration && docker build -t sternshawn/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sternshawn/expiration
      # Install doctl + token
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # Connect to our DO k8s cluster context
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # Run deploy + restart!
      - run: kubectl rollout restart deployment expiration-depl
